abstract class StaticData {
  static List<String> get categories => [
    'Automotive',
    'Cars & Vehicles',
    'Motorcycle & Scooters',
    'Car Accessories',
    'Tires & Wheels',
    'Electronics',
    'Mobile Phones',
    'Laptops & Computers',
    'Tablets',
    'Cameras & Photography',
    'TVs & Home Theater',
    'Audio & Headphones',
    'Gaming Consoles & Accessories',
    'Smartwatches & Wearables',
    'Home Appliances',
    'Refrigerators',
    'Washing Machines',
    'Microwaves & Ovens',
    'Vacuum Cleaners',
    'Air Conditioners',
    'Clothing & Fashion',
    'Men\'s Clothing',
    'Women\'s Clothing',
    'Kids\' Clothing',
    'Shoes & Footwear',
    'Bags & Handbags',
    'Watches & Jewelry',
    'Eyewear & Sunglasses',
    'Beauty & Personal Care',
    'Makeup & Cosmetics',
    'Skincare',
    'Haircare',
    'Perfumes & Fragrances',
    'Health & Wellness',
    'Fitness Equipment',
    'Dietary Supplements',
    'Medical Supplies',
    'Home & Furniture',
    'Living Room Furniture',
    'Bedroom Furniture',
    'Office Furniture',
    'Kitchen & Dining',
    'Bedding & Mattresses',
    'Home Decor',
    'Lighting & Lamps',
    'Gardening & Outdoor',
    'Toys & Baby Products',
    'Baby Gear',
    'Toys & Games',
    'Educational Toys',
    'Sports & Outdoors',
    'Bicycles & Accessories',
    'Camping & Hiking Gear',
    'Fishing Equipment',
    'Gym & Exercise Equipment',
    'Books & Stationery',
    'Fiction & Novels',
    'Educational & Academic',
    'Office Supplies',
    'Music & Instruments',
    'Guitars & Accessories',
    'Pianos & Keyboards',
    'Drums & Percussion',
    'DJ & Audio Equipment',
    'Pet Supplies',
    'Dog & Cat Supplies',
    'Fish & Aquarium Accessories',
    'Bird & Small Pet Supplies',
    'Food & Beverages',
    'Groceries',
    'Snacks & Beverages',
    'Organic & Healthy Food',
    'Specialty Foods',
    'DIY & Tools',
    'Power Tools',
    'Hand Tools',
    'Building Materials',
    'Automotive Tools',
    'Security & Surveillance',
    'CCTV Cameras',
    'Home Security Systems',
    'Smart Locks',
    'Industrial & Business Supplies',
    'Office Equipment',
    'Packaging & Shipping',
    'Electrical & Hardware',
  ];

  /// WILLAYAS DE L'ALGERIE
  static List<String> get regions => [
    'Adrar',
    'Chlef',
    'Laghouat',
    'Oum El Bouaghi',
    'Batna',
    'Béjaïa',
    'Biskra',
    'Béchar',
    'Blida',
    'Bouira',
    'Tamanrasset',
    'Tébessa',
    'Tlemcen',
    'Tiaret',
    'Tizi Ouzou',
    'Alger',
    'Djelfa',
    'Jijel',
    'Sétif',
    'Saïda',
    'Skikda',
    'Sidi Bel Abbès',
    'Annaba',
    'Guelma',
    'Constantine',
    'Médéa',
    'Mostaganem',
    'M\'Sila',
    'Mascara',
    'Ouargla',
    'Oran',
    'El Bayadh',
    'Illizi',
    'Bordj Bou Arreridj',
    'Boumerdès',
    'El Tarf',
    'Tindouf',
    'Tissemsilt',
    'El Oued',
    'Khenchela',
    'Souk Ahras',
    'Tipaza',
    'Mila',
    'Aïn Defla',
    'Naâma',
    'Aïn Témouchent',
    'Ghardaïa',
    'Relizane',
  ];
}
